### ISSUE TITLE
Publish on Crates.io

### ISSUE THREAD

**Issue by tgross35** [Techie-Pi/doxygen-rs#4]
Hello,

Is there any reason this isn't published on Crates.io? Even if it's unfinished, a 0.1.x series would make it much nicer to control versions.

Currently the best way is to specify the git hash, e.g.

```toml
doxygen-rs = { git = "https://github.com/Techie-Pi/doxygen-rs.git", rev = "a7fee318" }
```

**Comment by Techie-Pi** [comment]
This is actually something I was going to do, but things happened in my life and I forgot!
Give me an hour or so to publish it :)

**Comment by Techie-Pi** [comment]
Done! https://crates.io/crates/doxygen-rs
I'll close this, but if any problem arises, feel free to re-open the issue :)

**Comment by tgross35** [comment]
That’s great, thank you!
